name: rescue_my_beauty
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  sprung: ^3.0.0
  bonfire: ^2.6.3
  flame_audio: ^1.3.0
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.5
  flame_splash_screen: ^0.1.0
  flutter_smart_dialog: ^4.5.3+6
  ff_annotation_route_library: ^3.0.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3

flutter:

  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/emotes/
    - assets/images/enemy/
    - assets/images/joystick/
    - assets/images/enemy/boss/
    - assets/images/enemy/mini_boss/
    - assets/images/enemy/little_monster/
    - assets/images/enemy/medium_monster/
    - assets/images/items/
    - assets/images/player/
    - assets/images/tiles/


  fonts:
    - family: pixel
      fonts:
        - asset: fonts/font_pixel.ttf
    - family: cn
      fonts:
        - asset: fonts/Slideqiuhong-Regular.ttf
