// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import
const List<String> routeNames = <String>[
  'rescue://gamepage',
  'rescue://homepage',
];

class Routes {
  const Routes._();

  /// 'GamePage'
  ///
  /// [name] : 'rescue://gamepage'
  ///
  /// [routeName] : 'GamePage'
  ///
  /// [constructors] :
  ///
  /// GamePage : [Key? key]
  static const String rescueGamepage = 'rescue://gamepage';

  /// 'HomePage'
  ///
  /// [name] : 'rescue://homepage'
  ///
  /// [routeName] : 'HomePage'
  ///
  /// [constructors] :
  ///
  /// HomePage : [Key? key]
  static const String rescueHomepage = 'rescue://homepage';
}
