name: build windows
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*

jobs:
  build:
    name: Release build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Setup flutter
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: stable
          flutter-version: '3.0.5'

      - name: Build Windows
        run: |
          Copy-Item -Path pubspec.yaml -Destination assets -Force
          flutter config --enable-windows-desktop
          flutter build windows --release --no-tree-shake-icons
          dir build/windows/runner/Release
          Compress-Archive -Path build/windows/runner/Release/* windows-win32-release.zip -Force
      - name: Release build
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: "*-release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.TAG }}